import type { AnalysisResult } from '../types';

/**
 * Generates a comprehensive markdown summary report of the social media analysis
 */
export function generateMarkdownReport(result: AnalysisResult): string {
  const date = new Date(result.analyzedAt).toLocaleString();

  return `# 📊 Social Media Content Analysis Report
**Generated on:** ${date}
**Overall Engagement Score:** ${result.overallScore} / 100

---

## 🎯 Executive Summary
- **Primary Tone:** ${result.tone.primary} (${result.tone.confidence}% confidence)
- **Sentiment:** ${result.sentiment.type} (Score: ${result.sentiment.score.toFixed(2)})
- **Readability Grade:** ${result.readability.gradeLevel} (Flesch Score: ${result.readability.fleschScore}/100)
- **Reading Time:** ~${result.readability.readingTimeSeconds} seconds (${result.readability.wordCount} words, ${result.readability.characterCount} chars)

---

## 🔍 Score Breakdown
| Component | Score | Status |
| :--- | :--- | :--- |
| **Opening Hook** | ${result.scoreBreakdown.hook}/100 | ${result.scoreBreakdown.hook >= 75 ? '🟢 Strong' : '🟡 Needs Boost'} |
| **Clarity & Flow** | ${result.scoreBreakdown.clarity}/100 | ${result.scoreBreakdown.clarity >= 70 ? '🟢 Clear' : '🟡 Dense'} |
| **Call to Action (CTA)** | ${result.scoreBreakdown.cta}/100 | ${result.callToAction.detected ? '🟢 Detected' : '🔴 Missing'} |
| **Emotional Resonance** | ${result.scoreBreakdown.emotionalResonance}/100 | 🟢 High |
| **Visual Formatting** | ${result.scoreBreakdown.formatting}/100 | 🟢 Scannable |

---

## 🪝 Hook Analysis
- **Detected Hook:** "${result.hookAnalysis.hookText}"
- **Hook Type:** ${result.hookAnalysis.type}
- **Evaluation:** ${result.hookAnalysis.critique}
- **Suggested Alternative:**
  > ${result.hookAnalysis.suggestedAlternative}

---

## 📱 Multi-Platform Readiness
### 1. LinkedIn (${result.platformScores.linkedin.score}/100)
- Character Count: ${result.platformScores.linkedin.characterCount} / ${result.platformScores.linkedin.characterLimit}
- Recommendations:
${result.platformScores.linkedin.specificTips.map(t => `  - ${t}`).join('\n')}

### 2. Twitter / X (${result.platformScores.twitter.score}/100)
- Character Count: ${result.platformScores.twitter.characterCount} / 280
- Status: ${result.platformScores.twitter.status}
- Recommendations:
${result.platformScores.twitter.specificTips.map(t => `  - ${t}`).join('\n')}

### 3. Instagram (${result.platformScores.instagram.score}/100)
- Recommendations:
${result.platformScores.instagram.specificTips.map(t => `  - ${t}`).join('\n')}

### 4. Facebook (${result.platformScores.facebook.score}/100)
- Recommendations:
${result.platformScores.facebook.specificTips.map(t => `  - ${t}`).join('\n')}

---

## 💡 Top Improvement Recommendations
${result.suggestions.map((s, idx) => `### ${idx + 1}. [${s.impact} Impact] ${s.title}
${s.description}
${s.actionableExample ? `\n> **Example Fix:**\n> ${s.actionableExample}` : ''}
`).join('\n')}

---

## 🏷️ Hashtag Strategy
- **Extracted Tags:** ${result.hashtags.extracted.length > 0 ? result.hashtags.extracted.join(' ') : 'None'}
- **Recommended High-Impact Tags:** ${result.hashtags.suggested.join(' ')}
- **Analysis:** ${result.hashtags.analysis}

---

## ✍️ Generated A/B Optimization Variants

${result.variants.map(v => `### 📌 ${v.title} (${v.estimatedEngagementBoost})
*${v.description}*

\`\`\`text
${v.content}
\`\`\`
`).join('\n')}

---
*Report generated by Social Media Content Analyzer*
`;
}

/**
 * Downloads a string content as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/markdown'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
